version: '3.1'

services:
  jenkins:
     image: dtulyakov/jenkins
     build: .
     container_name: Jenkins
     env_file: .env
     volumes:
         - /etc/localtime:/etc/localtime:ro
         - /var/run/docker.sock:/var/run/docker.sock
         - /usr/bin/docker:/usr/bin/docker
         - jenkins_home:/var/jenkins_home
     restart: unless-stopped
     network_mode: host
     #ports:
         #- 8080:8080
         #- 50000:50000

  nginx:
     image: nginx:alpine
     container_name: Nginx
     env_file: .env
     volumes:
         - ./data/nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
         - ./data/nginx/ssl:/etc/nginx/ssl:ro
     restart: unless-stopped
     network_mode: host

volumes:
  jenkins_home:
    external:
        name: jenkins_home
