version: '3.1'

services:
  jenkins:
     image: dtulyakov/jenkins
     build: .
     container_name: Jenkins
     env_file: .env
     volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /usr/bin/docker:/usr/bin/docker
         - jenkins_home:/var/jenkins_home
     restart: unless-stopped
     ports:
         - 8080:8080
         - 50000:50000
     network_mode: host

volumes:
  jenkins_home:
    external:
        name: jenkins_home
